name: Build

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Chceckout code
        uses: actions/checkout@v2
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-debug-
      - name: Build project
        env:
          DATABASE_URL: 'sqlite:db/bestiary.db'
        run: |
          touch db/bestiary.db
          sqlite3 db/bestiary.db ".read db/migrations/V1_init.sql"
          cargo build --all --all-targets
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: baca-${{ runner.os }}
          path: ./target/debug/bestiary*/
      - name: Run tests
        run: cargo test --verbose
      - name: Run linter
        env:
          DATABASE_URL: 'sqlite:db/bestiary.db'
        run: cargo clippy --all-features -- -D warnings
