name: Build

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Chceckout code
        uses: actions/checkout@v2
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-debug-
      - name: Check project
        env:
          DATABASE_URL: 'sqlite:db/bestiary.db'
        run: |
          touch db/bestiary.db
          sqlite3 db/bestiary.db ".read db/migrations/V1_init.sql"
          cargo clippy --package bestiary --all-features -- -D warnings
      - name: Run tests
        env:
          DATABASE_URL: 'sqlite:db/bestiary.db'
        run: cargo test --verbose
      - name: Check formatting
        run: cargo fmt --all -- --check
